### ISSUE TITLE
Riedel Micron and ember+

### ISSUE THREAD

**Issue by booguiseb** [dewiweb/MCxOSCnext#15]
Hi,
I would like to connect a Micron instead of a LAWO MC to your MCxOSC but i didn't find the way of adding my own path.
And is the path format like frame.node.fontion.input...., cause usually (like in bitfocus companion) the path is 1.1.2.0.3
can we change interger to string ?

I would love to use OSC command to control those Riedel Micron frame.
thanks for any help

**Comment by dewiweb** [comment]
Actually, there's no support for string value but it could be a enhancement for future release ( maybe it works yet but I have not test it). Can you tell me which version you've tested because I made some changes in last beta version with ability to edit connections settings directly in table? The format of ember+ paths is the same as the one used by bitfocus. You can retrieve paths of your device with lawo ember+ viewer downloadable on their github repository. I could test and report next week connection with MicronUHD. If you've got any background with json you can edit connections directly a  json file as explain in the readme.md file.

**Comment by booguiseb** [comment]
Bonsoir,

Je vais continuer en français , a ce que j’ai vu nous sommes tout les deux de rennes.

J’ai essayer version 1.01 pour windows sur GitHub . Effectivement je vais plutôt re-tester avec une version beta récente
J’ai bien récupéré les path de mon Micron ave ember+ viewer, mais pour compagnon on utilise directement 1.1.2.3 par exemple et pas le noms du chemin.
J’essaierai demain d’éditer le fichier json, mais j’ai eu l’impression qu’il ne le chargeais pas ensuite.

Serait il possible de créer un template micron dans la même idée que celui pour la MC ?

Bonne soirée

**Comment by dewiweb** [comment]
Dans la dernière beta tu as aussi une fenêtre pour jeter un œil aux logs. Tu peux rentrer le path ember+ en 1.1.2..... Dans mon souvenir ça marche aussi mais il faut vraiment que je test sur compactpro et micronUHD. Pour ce qui est de faire un template dédié au Micron ce n'est pas dans les tuyaux. Je pense que l'utilisation du fichier json est déjà un bon moyen de ce construire un modèle. Autre question : la connection à ton Micron s'établit bien (voyant en haut à gauche au vert)?

**Comment by booguiseb** [comment]
Oui c’était bien vert, je teste ca demain.

Merci et bonne soirée

**Comment by booguiseb** [comment]
Bonjour,

Je viens de tester l’avant dernière version (problème de connection à ember avec la toute dernière), il y a un bug sur mon PC, voir photo, on ne peut pas choisir certain paramètre dans la ligne.

Le led verte clignote bien quand j’envoie une trame OSC, mais je ne vois rien dans le log. Il serait tres pratique de voir les trames reçus et émises par le logiciel.

Pour le moment je bloque, je ne comprends pas si je dois envoyer au micron un Integer, un String … et comment cela est formaté par le MCxOSC

A suivre

Bonne journée

**Comment by dewiweb** [comment]
Bonjour, il manque l'image liée au bug que tu indique dans ton dernier message.

**Comment by dewiweb** [comment]
Il y a effectivement un bug sur la dernière beta(j'ai poussé un commit un peu dans la précipitation). Je suis en train de travailler sur l'intégration des valeurs "String"(qui ne fonctionnait jusqu'à présent que pour renvoyer le nom de la tranche de la MC²36 sélectionnée vers de l'OSC. J'ai fait des essais sur Micronuhd (j'arrive pour l'instant à changer des valeurs String) mais je dois encore pousser les tests. Pas sur par exemple que l'on puisse gérer directement les  crosspoint des matrices et à l'inverse de la Lawo , le Micron ne renvoit pas la valeur du path à la souscription....Je compte également intégrer la possibilité d'ajouter une ligne vide en fin de tableau de connections. À suivre...

**Comment by booguiseb** [comment]
Bonsoir,

Du coup le micron réagit bien à l’envoie de string ? Peut-on changer des valeurs comme le passage en mire de test sur les sorties ? Ou seulement les labels ?
Sur l’ember + viewer, il semble que les valeurs modifiables qu’elle soit booléenne  ou integer, proviennent toujours d’une valeur convertit d’un String (je ne sais pas si je suis clair)

Avec companion, pour faire un commute dans la matrice il faut lancer deux commande, une foie un Matrix Set Connection et ensuite un Matrix Connect.

Je suis impatient de tester la prochaine version, une integration complete du micron en OSC pourrait s’avérer tres pratique.

Bon code

**Comment by dewiweb** [comment]
J'ai envoyé une nouvelle beta mais je n'ai pas eu bcp de temps pour pousser les tests

**Comment by booguiseb** [comment]
hello, je n'ai pas accès au micron avant 15 jours, je teste ta dernière version à ce moment là.
Tu as accès à ce materiel à quel endroit sur rennes ?
bonne soirée

**Comment by dewiweb** [comment]
Aux champs Libres

**Comment by dewiweb** [comment]
Et toi?

**Comment by booguiseb** [comment]
Je suis intermittent, c’est tres variable, mais la j’étais et je retourne à malte pour un ESL pro league avec GRAVITY MEDIA.
On a un contrôleur VSM lawo , une MC56 , une dizaine de Micron, mélangeur Kahuna et grille Sirius. 
Et un peu de temps pour tester des trucs. Du coup quand j’ai vue ton soft, ca m’a donné des idées.

Je ne savais pas qu’il y avait ce genre d’équipement aux champs libres.

**Comment by dewiweb** [comment]
Passes nous voir à l'occasion. On pourra discuter des usages que tu souhaites faire de mon soft.

**Comment by booguiseb** [comment]
hello, je suis de retour sur le Micron, j'ai essayé la dernière version du soft mais elle ne semple pas se connecter au Micron

**Comment by dewiweb** [comment]
J'étais sur un autre projet. Du coup je n'ai pas eu le temps d'avancer là dessus. Pour info il y a un module companion bitfocus qui est sorti pour mediornet, avec gestion des matrices

**Comment by dewiweb** [comment]
J'étais sur un autre projet. Du coup je n'ai pas eu le temps d'avancer là dessus. Pour info il y a un module companion bitfocus qui est sorti pour mediornet, avec gestion des matrices. Je vais jeter un coup d'œil ce WE concernant le problème de connexion

**Comment by dewiweb** [comment]
J'arrive à me connecter au Micron mais pas à récupérer des valeurs. A chaque fois j'ai droit à un request timeout....

**Comment by dewiweb** [comment]
Un exemple de fichier session pour gerer les testpatterns sur une sortie:
```js
[
  {
    "path": "mediornet.frames.node_126935767.slots.slot_2_5120.channels.channel_1.parameters.testPattern",
    "factor": "",
    "address": "/test",
    "type": "Integer",
    "math": "",
    "min": "/0",
    "max": "/1"
  }
]
````
Tu envoies ensuite un integer sur l'addresse osc /test (il faut par contre connaitre l'id de ta frame micronUHD)

**Comment by booguiseb** [comment]
Hello,

Merci pour le partage, je n’ai plus accès au Micron, la presta est terminé. Je retenté ca des que possible.

Tu penses qu’on peut adapter ton code pour un raspberry PI.  Mon idée étant d’avoir une boite GPI in et out et de les retrouver en EMBER+

Bonne journée 

Seb

**Comment by dewiweb** [comment]
Beta for armv7l(rpi) to test:

[https://github.com/dewiweb/MCxOSCnext/releases/download/v2.1.0-beta.5/mcxoscnext-2.1.0-beta.5-armv7l.AppImage](https://github.com/dewiweb/MCxOSCnext/releases/download/v2.1.0-beta.5/mcxoscnext-2.1.0-beta.5-armv7l.AppImage)

Je ne suis pas sur de bien suivre:
Tu veux utiliser directement les gpio du rpi pour gerer des commandes ember+?

J'ai également rajouté un dossier examples avec [un exemple de fichier *.session](https://github.com/dewiweb/MCxOSCnext/blob/ae2c75560e97a38d0e5873e290170d82f6e107f7/examples/Mediornet_V_Matrix_Names.session) pour gérer les nom d'entrées/sorties d'une matrice video 4X4 de mediornet. 

Autre point:  Tu peux maintenant copier directement le path ember+ depuis emberplusview( commences à copier à partir de "mediornet/" -- sans l'adresse/le port et le premier "/" du path) et le coller dans le tableau de connections.

Il arrive que le "Go" ne marche pas la première fois, il faut insister et clicquer plusieurs fois jusqu'à avoir une valeur dans le tableau( 4 fois dans mon cas/ du à une difference d'implémentation ember+ entre Lawo et Riedel je penses).
Une fois la première connection active le Go marche Nickel sur les autres...

**Comment by dewiweb** [comment]
J'ai modifié la manière de selectionner le path ember+ dans la dernière release publiée.
ça ressemble maintenant un peu plus au viewer ember+fourni par lawo.
Un arbre à gauche, puis quand un paramètre est sélectionné --> son contenu s'affiche à droite et un bouton submit permet d' ajouter ce paramètre au tableau.
Pas encore eu l'occasion de tester un production, je testerai ça la semaine pro...

**Comment by booguiseb** [comment]
Hello, merci pour l’update, je teste ca de mon coté dès que possible .
